config/routes.rb
Rails.application.routes.draw do
  resources :customer_reviews
  root 'welcome#page', as: '/'
  resources :users
  resources :tasks

  get "customer_service/:id", to: "customer_services#show", as: "customer_service"
  post "customer_service/:id", to: "customer_services#show", as: "customer_service/solve"
  patch 'customer_service/:id', to: 'customer_services#update', as: 'customer_service/solved'

  get "bug/:id", to: "bugs#show", as: "bug"
  post "bug/:id", to: "bugs#show", as: "bug/solve"
  patch 'bug/:id', to: 'bugs#update', as: 'bug/solved'

  resources :customer_services, to: [:index, :create, :new]
  resources :bugs, to: [:index, :create, :new]

  resources :employees

  get "profile/:id", to: "customers#show", as: "customer"
  post "profile/:id", to: "customers#show", as: "customer/bug"
  get "signup", to: "users#new", as: "signup"
  get 'login', to: "sessions#new", as: "login"
  post 'logout', to: 'sessions#destroy', as: 'logout'
  post 'sessions', to: 'sessions#create', as: 'sessions'
  resources :customers, only: [:index, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bug.rb
class Bug < ApplicationRecord
  has_one :task
  has_one :employee, through: :task
  belongs_to :customer
  has_many :customer_reviews, as: :ticket
  validates :name, :description, presence: true


  def task
    Task.create(bug: self, employee: employee)
  end

  private

  def employee
    Employee.all.select {|employee| employee.department == 'Bug'}.first
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one :user
  has_many :customer_reviews
  has_many :customer_services
  has_many :bugs
  validates :name, :email, presence: true
  validates :name, :email, uniqueness: true
end

app/models/customer_review.rb
class CustomerReview < ApplicationRecord
  belongs_to :task
  belongs_to :employee
  belongs_to :customer
  belongs_to :ticket, polymorphic: true
end

app/models/customer_service.rb
class CustomerService < ApplicationRecord
  has_one :task
  has_one :employee, through: :task
  belongs_to :customer
  has_many :customer_reviews, as: :ticket
  validates :name, :description, presence: true

  def task
    Task.create(customer_service: self, employee: employee)
  end


  private

  def employee
    Employee.all.select {|employee| employee.department == 'CX'}.first
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_one :user
  has_many :customer_reviews
  has_many :tasks
  has_many :bugs, through: :tasks
  has_many :customer_service, through: :tasks

end

app/models/task.rb
class Task < ApplicationRecord
  has_one :customer_review
  belongs_to :employee
  belongs_to :customer_service, optional: true
  belongs_to :bug, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :employee, optional: true
  belongs_to :customer, optional: true
  has_secure_password

  def associate_employee(department)
    Employee.create(name: self.name, department: department, email: self.email, user: self)
    self.account_type = 'employee'
    self.save
  end

  def associate_customer
    Customer.create(name: self.name, email: self.email, user:self)
    self.account_type = 'customer'
    self.save
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_action :authorized


  def index
    # byebug
    if current_user.account_type == 'customer'
      @bugs = current_user.customer.bugs
    elsif current_user.account_type == 'employee'
      @bugs = current_user.employee.customer_services
    end
  end

  def new
    @bug = Bug.new
  end

  def create
    @bug = Bug.create(bug_params)
    @bug.task
    redirect_to bugs_path
  end

  def show
    @bug = Bug.find(params[:id])
  end

  def update
    @bug = Bug.find(params[:id])
    @bug.update(bug_params)
    redirect_to @bug
  end

  private

  def bug_params
    params.require(:bug).permit(:name, :description, :customer_id,:solution_description, :completed, :type)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.valid?
      @customer.save
      redirect_to @customer
    else
      redirect_to login_path
    end
  end

  def show
    @customer = Customer.find(params[:id])
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :password, :password_confirmation, :email, :type, :revbutton)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end
  def show
    @employee = Employee.find(params[:id])
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      if @user.account_type == 'customer'
        redirect_to customer_path(@user.customer)
      elsif @user.account_type == 'employee'
        redirect_to employee_path(@user.employee)
      end
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.associate_customer
      @user.save
      redirect_to login_path
    else
      redirect_to signup_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation, :email, :type)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base

  def page

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/customer_reviews_helper.rb
module CustomerReviewsHelper
end

app/helpers/customer_services_helper.rb
module CustomerServicesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bugs/_form.html.erb
<%= form_for @bug do |f|%>
  <div class="col-lg-12 mb-6">
    <%= f.label "Solution's Description"%><br><br>
    <%= f.text_area :solution_description%><br><br>
  </div>
  <div class="col-lg-12 mb-6">
  <%= f.check_box :completed, {}, true, false%>
  <%= f.label "Solved"%><br><br>
</div>
<div>
  <%= f.submit "Submit",class: "btn btn-info"%>
</div>
<%end%>

app/views/bugs/_review_form.html.erb
<div>
  <p>Review Form</p>
</div>

<div>
  <%=form_for @bug.customer_reviews.build, class:'auth-form-body mt-3' do |f|%>
  <div class="col-lg-12 mb-6">
    <%= f.label :rating%>
    <%= f.select :rating, [1,2,3,4,5]%>
  </div>
  <div class="col-lg-12 mb-6">
    <%= f.label :description%><br>
    <%= f.text_area :description%>
  </div><br>
  <div class="col-lg-12 mb-6">
    <%= f.hidden_field :customer_id, value: @bug.customer.id%>
    <%= f.hidden_field :employee_id, value: @bug.task.employee.id%>
    <%= f.hidden_field :task_id, value: @bug.task.id%>
    <%= f.hidden_field :ticket_id, value: @bug.id%>
  </div>
  <div class="col-lg-12 mb-6">
    <%=f.submit "Submit Review",class: "btn btn-info"%>
  </div>
  <%end%>
</div>

app/views/bugs/index.html.erb
<div class="container">
  <div class="title">
    <h1>Bugs</h1>
  </div>
  <div id="customer" class= "bug auth-form-body mt-3">
    <% if @bugs.length < 1%>
      No Complaints open
      <%= link_to 'profile/4', class: "btn btn-info" do %>Back
       <% end %>
    <%else%>
      <%@bugs.each do |bug|%>
        <li class='li'><%=link_to bug.name, bug%></li>
      <%end%>
      <%= link_to customer_path(@bugs.first.customer.id), class: "btn btn-info" do %>Back
       <% end %>
    <%end%>
  </div>
</div>

app/views/bugs/show.html.erb
<%if logged_in?.account_type == "employee"%>
  <div class="col-lg-12 mb-6 name">
    <p><%=@bug.task.employee.name%></p>
  </div>
  <div class="bug auth-form-body mt-5">
    <div class="content">
      <div class="b">
        <p>Customer Name: <%= @bug.customer.name%></p>
        <p>Bug Name: <%= @bug.name%></p>
        <p>Bug Description: <%= @bug.description%></p>
      </div>
      <%if @bug.completed == true%>
        <p>Problem Solved</p>
        <p>Solution Description: <%= @bug.solution_description%></p>
        <%= link_to "Back", employee_path(@bug.task.employee)%>
      <%elsif params[:type] == nil%>
        <%= form_tag class: 'auth-form-body mt-3 bug_solve' do |t|%>
          <div class="col-lg-12 mb-6">
            <%=radio_button_tag "type", '1'%>
            <%= label_tag "Solve this Problem?"%><br><br>
          </div>
          <div>
            <%=submit_tag "Submit",class: "btn btn-info"%>
          </div><br><br>
          <div>
          <%= link_to employee_path(@bug.task.employee), class: "btn btn-info" do %>Back
        <% end %>
          </div>
        <% end %>
      <%else%>
      <div class="container">
        <%= render "form"%>
      </div>
      <%end%>
    </div>
  <%elsif logged_in?.account_type == "customer"%>
      <div class="col-lg-12 mb-6 name">
        <p><%=@bug.customer.name%></p><br>
      </div>
      <%if @bug.completed == true%>
      <div class="col-lg-12 mb-6 name">
        <p>Solution - <%= @bug.solution_description%></p><br>
      </div>
        <%if params[:revbutton] == "1"%>
          <div class="container">
            <div class="form fixed-top">
              <%=render "review_form"%><br>
              <%= link_to customer_path(@bug.customer), class: "btn btn-info" do %>Back
              <% end %>
            </div>
          </div>
        <%else%>
        <div class="container">
          <div class="form fixed-top">
              <%= form_tag class:'auth-form-body mt-3 bug_solve' do |f|%>
                <div class="col-lg-12 mb-6">
                  <%=radio_button_tag "revbutton", '1'%>
                  <%= label_tag "Add Review?"%><br><br>
                </div>
                <div class="col-lg-12 mb-6">
                  <%=submit_tag "Submit",class: "btn btn-info"%><br><br>
                  <%= link_to customer_path(@bug.customer), class: "btn btn-info" do %>Back
                  <% end %>
                </div>
              <% end %>
              <%end%>
            </div>
          </div>
        <%end%>
      <%else%>
        <div class="col-lg-12 mb-6 name">
          <p>Complain is open</p><br>
        </div>
      <%end%>
</div>

app/views/customers/_bug_form.html.erb
<div>
  <p>Bugs</p>
</div>

<div>
  <%=form_for @customer.bugs.build, class:'auth-form-body mt-3' do |f|%>
    <div>
      <p><%= f.label :name%></p>
      <%= f.text_field :name%>
    </div><br>
    <div>
      <p><%= f.label :description%></p>
      <%= f.text_area :description%>
    </div><br>
    <div>
      <%= f.hidden_field :customer_id, value: @customer.id%>
      <%=f.submit "Create Complaint", class: "btn btn-info"%>
    </div><br>
    <div>
      <%= link_to params[:type] = nil, class: "btn btn-info" do %>Back
       <% end %>
    </div>
  <%end%>
</div>

app/views/customers/_customer_service_form.html.erb
<div>
  <p>Customer Service</p>
</div>

<div>
  <%=form_for @customer.customer_services.build, class:'auth-form-body mt-3' do |f|%>
    <div>
      <p><%= f.label :name%></p>
      <%= f.text_field :name%>
    </div><br>
    <div>
      <p><%= f.label :description%></p>
      <%= f.text_area :description%>
    </div><br>
    <div>
      <%= f.hidden_field :customer_id, value: @customer.id%>
      <%=f.submit "Create Complaint", class: "btn btn-info"%>
    </div><br>
    <div>
      <%= link_to params[:type] = nil, class: "btn btn-info" do %>Back
       <% end %>
    </div>
  <%end%>
</div>

app/views/customers/_form.html.erb
<%=form_for @customer do |f|%>
  <%= f.label :name%>
  <%= f.text_field :name%><br>
  <%= f.label :email%>
  <%= f.text_field :email%><br>
  <%= f.label :password%>
  <%= f.password_field :password%><br>
  <%= f.label :password_confirmation%>
  <%= f.password_field :password_confirmation%><br>
  <%=f.submit%>
<%end%>

app/views/customers/index.html.erb
<h1>Bugs</h1>
<div class="container">
    <% @customers.each do |customer| %>
    <% customer.bugs.each do |bug| %>
      <li><%= bug.description %></li>
    <%end%>
  <%end%>
  <h1>customer service </h1>
  <% @customers.each do |customer| %>
    <% customer.customer_services.each do |customer_service| %>
      <li><%= customer_service.description %></li>
    <%end%>
  <%end%>

  <h1>bugs</h1>
    <% @customers.each do |customer| %>
      <li><%= link_to customer.name, customer %></li>
  <%end%>

</div>

app/views/customers/show.html.erb
<div class="container">

  <div class="title">
    <h1>Welcome <%= @customer.name %></h1>
  </div>

  <div id="customer" class= "bug auth-form-body mt-3">
    <%if params[:type] == nil%>
      <div>
        <% if @customer.bugs.length >= 1 %>
          <%= link_to bugs_path, class: "btn btn-info" do %>My Bugs
          <% end %>
        <%else%>
          No Complaints open
        <% end %>
      </div><br>
      <div>
        <% if @customer.customer_services.length >= 1 %>
          <%= link_to customer_services_path, class: "btn btn-info" do %>My Customer Service
          <% end %>
        <%else%>
          No Complaints open
        <% end %>
      </div><br>
      <p>Choose a complaint type</p>
      <%= form_tag do |f|%>
        <div>
          <p><%=radio_button_tag "type", '0'%>
          <%= label_tag 'Customer Service'%></p>
        </div>
        <div>
          <p><%=radio_button_tag "type", '1'%>
          <%= label_tag 'Bugs'%></p>
        </div>
        <div>
        <%=submit_tag 'Choose',class: "btn btn-info"%>
      <%end%>
        </div>
      <%elsif params[:type] == '0'%>
      <div>
        <%=render 'customer_service_form'%>
      </div>
      <%elsif params[:type] == '1'%>
      <div>
        <%=render 'bug_form'%>
      </div>
      <%end%>
  </div>
</div>

app/views/employees/index.html.erb
<% @employees.each do |employee| %>
  <li><%=link_to employee.name, employee%></li>
<%end%>

app/views/employees/show.html.erb
<div class="col-lg-12 mb-6 name">
  <p>Welcome <%= @employee.name %></p> <br>
  <p><%= @employee.department %></p>
</div>


<div id="employee" class="bug auth-form-body mt-3">
    <div class="content">
      <% @employee.tasks.each do |task| %>
        <ul>
          <%if task.bug && !task.bug.solution_description%>
            <li class="li"><%=link_to task.bug.name, task.bug%></li>
          <%elsif task.customer_service && !task.customer_service.solution_description%>
            <li class="li"><%= link_to task.customer_service.name, task.customer_service%></li>
          <%else%>
            solved
          <%end%>
        </ul>
      <% end %>
    </div>
</div>

app/views/users/_form.html.erb
<%=form_for @user, class:'auth-form-body mt-3' do |f|%>
  <div class="col-lg-12 mb-6">
    <%= f.label :name%><br>
    <%= f.text_field :name%>
  </div><br>
  <div class="col-lg-12 mb-6">
    <%= f.label :email%><br>
    <%= f.text_field :email%>
  </div><br>
  <div class="col-lg-12 mb-6">
    <%= f.label :password%><br>
    <%= f.password_field :password%>
  </div><br>
  <div class="col-lg-12 mb-6">
    <%= f.label :password_confirmation%><br>
    <%= f.password_field :password_confirmation%><br>
  </div><br>
  <div>
    <%=f.submit "Submit", class: "btn btn-info"%>
  </div>
<%end%>

app/views/users/new.html.erb
<div class="container">
  <div class="form fixed-top">
    <div class="login-img">
      <%= image_tag "bug.png", :width => 100, :height => 100, :crop => :fill%>
    </div><br>
    <%= render 'form'%>
 </div>
</div>